### ISSUE TITLE
[Spike] Optimize ToListPool path

### ISSUE THREAD

**Issue by faustodavid** [faustodavid/ListPool#7]
At the moment we are faster than System.Collections.List creating a new instance using an IEnumerable source, but Linq "ToList()" is insane faster. We should analyze what can we do better to compete with Linq.

**Comment by SergeyMokin** [comment]
I will pick it up if you not started yet

**Comment by faustodavid** [comment]
You can go ahead :) You can see what is Linq doing under the hood. Additionally, maybe we can create an unchekedAdd(TSource item) method.
